### ISSUE TITLE
Eqep API - DISPLAY not found

### ISSUE THREAD

**Issue by gye-tgm** [TGM-HIT/eqep-api#12]
![screen shot 2015-02-09 at 16 26 40](https://cloud.githubusercontent.com/assets/2834414/6109077/93e13e38-b078-11e4-994e-3837c3fe8bf1.png)

**Comment by efrantar-tgm** [comment]
This is presumably because `pyplot` uses the DISPLAY defined in `/etc/matplotlibrc` which is in your case not configured correctly.

If your server does not have a UI/Display you can you the `Agg` display. You can either edit this in above mentioned config-file or set it dynamically with the following lines of code:

```
import matplotlib
matplotlib.use('Agg')
```

Note that this must be done before importing `pyplot` for the first time, so also before importing anything from the `eqep`-module.
